# pub keys
keys:
- &users:
    - &kent age1em9n3fvg9jphpsx055cv0t8u5wnxs64x2auddxsvjtuvg85kmerqp0wjg0
- &hosts: # nix-shell -p ssh-to-age --run 'cat /etc/ssh/ssh_host_ed25519_key.pub | ssh-to-age'
    - &greatblue age158lzfdas82aj2dayppkcv4xgs4u7m0uk7zul90sfpj8wxdavyuqqgv6ar2
    - &delaware age1pddnp2as3e76uqhk9uh3ff48jcua5st5px3cp35nmk2urem2xewq7vn6m4
    # Home manager installs:
    - &y700 age1ldfj8u2lmq7cntyu6hxtep9dy7z6gfesctltztuz4fwh2a7ww4qsywvjyn
    - &s24 age1ug0wd4d2tukuw2w7lzrpf2um8r2fxxr90xg7mphu07wwldnan3qsngdelh
    - &p80 age1h5e3z2s9w8faf7kx6xuq4yh36g5lf849p2zvx4jxln2gzdt2kucsr55c0g
    - &boox_air_nova_c age1u9vdsgf5x8qng69vf0fed03fl7rh0h0276pvjh90x9qyxtjq5uaq4cwlgf
    - &a9 age1h4x9vcyms6kkfwxgz5y8k3yk4g6vg0rn5wvenhmc632w8gvgascser0xqr

creation_rules:
     # path should be relative to location of this file (.sops.yaml)
#  - path_regex: secrets/secrets.yaml$
#    key_groups:
#    - age:
#      - *kent
#      - *greatblue
#      - *delaware
#      - *y700
#      - *s24
#      - *p80
#      - *boox_air_nova_c
#      - *a9
    #
  - path_regex: modules/servers/.*/.*.yaml$
    key_groups:
      - age:
        - *kent
        - *delaware
        - *greatblue
        - *y700
        - *s24
  - path_regex: modules/hosts/delaware/.*.yaml$
    key_groups:
      - age:
        - *kent
        - *delaware
        - *greatblue
        - *y700
        - *s24
