# pub keys
keys:
- &users:
    # nix-shell -p ssh-to-age --run "ssh-to-age -private-key -i ~/.ssh/signing_key > ~/.config/sops/age/keys.txt"
    - &kent            age1em9n3fvg9jphpsx055cv0t8u5wnxs64x2auddxsvjtuvg85kmerqp0wjg0
    - &kent_new        age15msunp0tetxut3lg4v5c32lmynkw29l2hhj3mguut3fmttdjw5esh4y4hf
    - &jess            age18j6d63zlrw2t4fd3sdqsxgv3yl6dn9rvzz3rxvf7lq96zwt27pesc7jmuy
- &hosts:
    # nix-shell -p ssh-to-age --run 'cat /etc/ssh/ssh_host_ed25519_key.pub | ssh-to-age'
    # Kent
    - &greatblue       age158lzfdas82aj2dayppkcv4xgs4u7m0uk7zul90sfpj8wxdavyuqqgv6ar2
    - &starling        age19md57qd8yqh7l5xvql8pynd6cvplnlx0jhmr9p3mz32z584869tswn04py
    - &delaware        age1pddnp2as3e76uqhk9uh3ff48jcua5st5px3cp35nmk2urem2xewq7vn6m4
    - &hamburger       age1cpxkxj7rgefd0yatd2muyhcty02ehxd08vdtfnhyyhulkhgy6pmqnrh3je
    # Jess
    - &cichlid         age1vhze94ngfzzsgtp45q6d8s4v9zt0234hxcnrk9x45ttz7r289vcq5yu7hw
    - &shoebill        age1pddnp2as3e76uqhk9uh3ff48jcua5st5px3cp35nmk2urem2xewq7vn6m4
    # Home manager installs:
    - &y700            age1ldfj8u2lmq7cntyu6hxtep9dy7z6gfesctltztuz4fwh2a7ww4qsywvjyn
    - &s24             age1ug0wd4d2tukuw2w7lzrpf2um8r2fxxr90xg7mphu07wwldnan3qsngdelh
    - &p80             age1h5e3z2s9w8faf7kx6xuq4yh36g5lf849p2zvx4jxln2gzdt2kucsr55c0g
    - &boox_air_nova_c age1u9vdsgf5x8qng69vf0fed03fl7rh0h0276pvjh90x9qyxtjq5uaq4cwlgf
    - &a9              age1h4x9vcyms6kkfwxgz5y8k3yk4g6vg0rn5wvenhmc632w8gvgascser0xqr

creation_rules:
# path should be relative to location of this file (.sops.yaml)
#  - path_regex: secrets/secrets.yaml$
#    key_groups:
#    - age:
#      - *kent
#      - *greatblue
#      - *delaware
#      - *y700
#      - *s24
#      - *p80
#      - *boox_air_nova_c
#      - *a9

  - path_regex: modules/servers/.*/.*.yaml$
    key_groups:
      - age:
        - *kent
        - *kent_new
        - *delaware
        - *greatblue
        - *y700
        - *s24
  - path_regex: modules/hosts/delaware/.*.yaml$
    key_groups:
      - age:
        - *kent
        - *kent_new
        - *delaware
  - path_regex: modules/hosts/greatblue/.*.yaml$
    key_groups:
      - age:
        - *kent
        - *kent_new
        - *greatblue
  - path_regex: modules/hosts/cichlid/.*.yaml$
    key_groups:
      - age:
        - *kent
        - *kent_new
        - *jess
        - *cichlid
  - path_regex: modules/hosts/shoebill/.*.yaml$
    key_groups:
      - age:
        - *kent
        - *kent_new
        - *jess
        - *shoebill
  - path_regex: modules/hosts/starling/.*.yaml$
    key_groups:
      - age:
        - *kent
        - *kent_new
        - *starling
  - path_regex: modules/hosts/hamburger/.*.yaml$
    key_groups:
      - age:
        - *kent
        - *kent_new
        - *hamburger
